title: Cork - the best material ever - Available in Germany
email: corkgermany@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://corkgermany.github.io/"

markdown: kramdown
sass:
  style: compressed
